### ISSUE TITLE
git release tags (missing tag 0.29)

### ISSUE THREAD

**Issue by anthraxx** [kazu-yamamoto/pgpdump#15]
Hey,

please can you synchronize your git tags with your released versions?
At your homepage you offer a 0.29 tarball, it would be great if you can tag the git commit for that version so i can pull a tarball from github and also have proper upstream watches so i gen notifications when new tags are pushed.

Thank you very much,
sincerely,
Levente

**Comment by kazu-yamamoto** [comment]
Sorry and done.

**Comment by anthraxx** [comment]
looks great, thank you very much for the fast response :+1:
