### ISSUE TITLE
new release?  (include changes since 0.35)

### ISSUE THREAD

**Issue by dkg** [kazu-yamamoto/pgpdump#39]
I see there are a few changes merged since v0.35 for over a year now, but they are not part of a release.  Should version 0.36 be tagged and released, or do you have pending work that you expect to make it into the next release?

**Comment by kazu-yamamoto** [comment]
Thank you for reminder.
I will.

**Comment by kazu-yamamoto** [comment]
v0.36 has been released.

http://www.mew.org/~kazu/proj/pgpdump/en/
