### ISSUE TITLE
Update CHANGES

### ISSUE THREAD

**Issue by stefanholek** [kazu-yamamoto/pgpdump#9]
Hi Kazu,

Seems like you forgot to update CHANGES for 0.29. Let me suggest the following:

  0.29 2014/08/01
- Adaption for Fedora packaging.
- Ignore whitespace when decoding Radix-64 input.
- Add support for GnuPG extensions in private subkeys.

Cheers

**Comment by veox** [comment]
Guess issue is OK to close?..

I'd like to note though that this git repo doesn't have 0.29 tagged.

**Comment by kazu-yamamoto** [comment]
Let's close this.
